### ISSUE TITLE
les questions sur les demandes

### ISSUE THREAD

**Issue by dingliefr123** [white-dev/JS-tests#1]
Tout d'abord, merci à vous de m'avoir donné la chance de faire le test. Après vu les demandes du test soigneusement, j'ai deux questions, je souhaites que vous puissiez m'expliquer un peu.
1. Concernant la **3ième demande** du test, `Implement function to get ALL albums of one user`. Selon moi, `one user`, donc, la paramètre  est  un object `user`,  il faut filter les albums juste dépdend ce object ou selon le `id` de user? C'est-à-dire on suppose que le `id` est déjà donné. Ou la propriété `id` de `user` est peut-être nullable, il faut trouver le `user` ciblé premièrement.
2. Comme la première question, la **4ième demande** `Implement function to get ALL titles of the one album`, on peut filter les albums dépend de ce object ou la propriété `id` de ce object? J'ai aussi remarqué que propriété `id` de chaque object `album`  est différént, C'est-à-dire une seul `id` ne correspond qu'à une seule `album` et un seul titre. Donc le résultat est toujours *le seul*, je ne sais pas si la pensée au-dessus est vraie. Il faut **votre confirmation**.

**Comment by dynamitebutcher** [comment]
Bonjour Lie,

1. On peut passer un objet user en paramètre, ou juste un id, au choix. Tu restes libre d'implémenter de la manière qui te semble la plus appropriée. Dans le cas d'un id null, à toi de gérer le cas pour ne pas que la fonction soit en erreur.
2. Pareil que la question 1, tu as le choix. Et oui, un album a un seul titre, pour le moment. Lors de l'entretien, nous changerons la structure de l'objet pour effectuer des modifications sur ta méthode.
